### ISSUE TITLE
Behinde a Proxy

### ISSUE THREAD

**Issue by Flonicar** [sivasamyk/graylog2-plugin-input-httpmonitor#1]
Hi,

thanks for the plugin. I have a problem to become a reuqest behind a proxy. In the intranet a request is no problem.
In the server.conf of graylog-server i defined the proxy. But without any resoult.

Do you have a idea what i can do?

**Comment by sivasamyk** [comment]
I assume you are talking about http_proxy_uri prameter in graylog.conf file. I have not tried this plugin behind a proxy.  I will try and let you know.

**Comment by sivasamyk** [comment]
I have updated release 1.0.2 with an option to add proxy URL from plugin configuration dialog. Download the latest jar from [here](https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/releases/download/v1.0.2/graylog2-plugin-input-httpmonitor-1.0.2.jar) and let me know your comments. Note that this jar will work with graylog v1.2

Let me know if you are using older releases.

**Comment by Flonicar** [comment]
Thank you for your fast reaction.
Im using the graylog v1.1.6 . Im sorry to tell you when i replace the jar with the 1.0.2 jar then all http monitor inputs are missing.

**Comment by Flonicar** [comment]
Log from system.log:

2015-09-11T08:55:29.943+02:00 ERROR [CmdLineTool] Plugin "HttpMonitorInput" requires version 1.2.0 - not loading!
....
2015-09-11T08:56:08.197+02:00 WARN  [PersistedInputsImpl] Cannot instantiate persisted input. No such type [org.graylog2.plugin.httpmonitor.HttpMonitorInput].
2015-09-11T08:56:08.200+02:00 WARN  [PersistedInputsImpl] Cannot instantiate persisted input. No such type [org.graylog2.plugin.httpmonitor.HttpMonitorInput].
2015-09-11T08:56:08.202+02:00 WARN  [PersistedInputsImpl] Cannot instantiate persisted input. No such type [org.graylog2.plugin.httpmonitor.HttpMonitorInput].

**Comment by sivasamyk** [comment]
plugin v1.0.2 requires minimum graylog v1.2. I will update v1.0.0 plugin with fix. please note the field names will change after update , to make it compatible with future versions.

**Comment by sivasamyk** [comment]
use the jar from [here](https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/releases/download/v1.0.0/graylog2-plugin-input-httpmonitor-1.0.0.jar). I have tested with graylog v1.1. Let me know if any issues.

**Comment by Flonicar** [comment]
Perfect.
everything works.

Thank you very much.

**Comment by sivasamyk** [comment]
I recommend you to try the content pack for httpmonitor input. You can download it form [here](https://raw.githubusercontent.com/sivasamyk/graylog-contentpack-httpmonitor/master/content_pack.json)
