### ISSUE TITLE
Do this plugin work for graylog 2.3?

### ISSUE THREAD

**Issue by kieulam141** [sivasamyk/graylog2-plugin-input-httpmonitor#10]
Hi.
Our cluster version is 2.3.So, Do this plugin work for graylog 2.3?
Thanks.

**Comment by sivasamyk** [comment]
Haven't tested with 2.3. Will check and update.

**Comment by sivasamyk** [comment]
@kieulam141 I just tested 1.0.5 version (https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/releases/download/v1.0.5/graylog2-plugin-input-httpmonitor-1.0.5.jar) of the plugin with graylog version 2.3.1 and itis  working file. Are you seeing any errors in graylog server logs?

**Comment by kieulam141** [comment]
Hi siva,
It works.
Thanks for good plugin.
