### ISSUE TITLE
Unable to see HTTP input on 1.3.3

### ISSUE THREAD

**Issue by hikarukujo** [sivasamyk/graylog2-plugin-input-httpmonitor#2]
Graylog-server 1.3.3 seems to be incompatible with the input plugin 1.0.2. There is no additional input type listed in the menu when loading the 1.0.2 jar file into plugins.

**Comment by sivasamyk** [comment]
I am not able to download 1.3.3 graylog server to reproduce this issue ( download is stuck at 99.9 % ). Can you let me know if you are seeing any exceptions in graylog server logs?

**Comment by sivasamyk** [comment]
I am able to see 'HTTP Monitor' option listed in 1.3.3 server Inputs UI. Let me know the contents of the graylog server logs.  Are you seeing something like this in graylog logs?

`Loaded plugins: [Anonymous Usage Statistics 1.2.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin], HttpMonitorInput 1.0.2 [org.graylog2.plugin.httpmonitor.HttpMonitorInputPlugin]]`

**Comment by hikarukujo** [comment]
Sorry, was out of the office and unable to test. In the grand scheme of things, it ended up being user permissions and nothing more. My apologies for the false issue report, works great!

I am wondering if there's a way to put a java key file in there so I can run the input against SSL sites? If not I'm okay running it against HTTP and just watching for the 302 response to go to SSL.

**Comment by sivasamyk** [comment]
If you want to connect to HTTPS URLs, giving the direct https URL should work. e.g. https://www.google.com instead of http://www.google.com

**Comment by hikarukujo** [comment]
I get "Request failed :java.net.ConnectException: General SSLEngine problem" as a reply, and I know the certs work because they pass validation in the browser and using openssl. Not sure if it's that the JVM is missing the root CAs in the trust store.

**Comment by sivasamyk** [comment]
I have updated the plugin to accept all certs. Download the latest jar from https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/releases/download/v1.0.2/graylog2-plugin-input-httpmonitor-1.0.2.jar and let me know if it solves your problem.

**Comment by hikarukujo** [comment]
That did it, getting 200 responses now. Thanks for your help!
