### ISSUE TITLE
Compatibility with Graylog 2.0

### ISSUE THREAD

**Issue by Benoss** [sivasamyk/graylog2-plugin-input-httpmonitor#3]
I don't have any _http metrics in the message
on the other hand everything else seems ok, including extracting the X-HEADERS data

Looking at the logs it looks like now you can't have nested values

> 2016-03-15 03:17:52,481 WARN : org.graylog2.plugin.Message - Keys must not contain a "." character! Ignoring field "http.monitor.responseTime"="207" in message [80e15510-ea5c-11e5-ad8b-62df949bdde0].
> 2016-03-15 03:17:52,481 WARN : org.graylog2.plugin.Message - Keys must not contain a "." character! Ignoring field "http.monitor.status"="200" in message [80e15510-ea5c-11e5-ad8b-62df949bdde0].
> 2016-03-15 03:17:52,482 WARN : org.graylog2.plugin.Message - Keys must not contain a "." character! Ignoring field "http.monitor.statusLine"="OK" in message [80e15510-ea5c-11e5-ad8b-62df949bdde0].
> 2016-03-15 03:17:52,482 WARN : org.graylog2.plugin.Message - Keys must not contain a "." character! Ignoring field "http.monitor.responseSize"="19518" in message [80e15510-ea5c-11e5-ad8b-62df949bdde0].
> 2016-03-15 03:17:52,483 WARN : org.graylog2.plugin.Message - Keys must not contain a "." character! Ignoring field "http.monitor.url"="https://www.google.co.nz" in message [80e15510-ea5c-11e5-ad8b-62df949bdde0].

![image](https://cloud.githubusercontent.com/assets/1436055/13766708/31dfd172-eac9-11e5-8951-afe857731a0a.png)

**Comment by Benoss** [comment]
Quick fix
https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/pull/4
This is probably going to break all your dashboards

**Comment by gqs** [comment]
Hello,

How i can update my ES 1.7 to 2.x when i have used this plugin ?

`Dots in field names lead to ambiguous field resolution, in fields: message:http\.monitor\.responseSize, message:http\.monitor\.responseTime, message:http\.monitor\.status, message:http\.monitor\.statusLine, message:http\.monitor\.url.`

Thanks

**Comment by sivasamyk** [comment]
You can download and use this jar [https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/releases/download/v1.0.2/graylog2-plugin-input-httpmonitor-1.0.3.jar](https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/releases/download/v1.0.2/graylog2-plugin-input-httpmonitor-1.0.3.jar) .

**Comment by gqs** [comment]
Thanks, but how i can update the ES 1.7 indices for replace the "dots" by "underscore" before ?

**Comment by sivasamyk** [comment]
This is breaking change in ES migration from 1.7. please see [http://docs.graylog.org/en/2.0/pages/upgrade.html#dots-in-field-names](http://docs.graylog.org/en/2.0/pages/upgrade.html#dots-in-field-names) for more info
