### ISSUE TITLE
Plugin does not appear in inputs on out-of-the-box Graylog 2.0.0

### ISSUE THREAD

**Issue by romanr** [sivasamyk/graylog2-plugin-input-httpmonitor#6]
Installed stock Graylog 2.0.0 from official AMI image
Copied plugin to plugin as instructed:

> /opt/graylog/server/plugin# ls -l
> total 14756
> -rw-r--r-- 1 root root 2111402 Mar 15 09:19 graylog2-plugin-input-httpmonitor-1.0.3.jar
> -rw-r--r-- 1 root root 1669275 Apr 28 16:03 graylog-plugin-collector-1.0.0.jar
> -rw-r--r-- 1 root root 1541788 Apr 28 16:03 graylog-plugin-enterprise-integration-1.0.0.jar
> -rw-r--r-- 1 root root 6452191 Apr 28 16:03 graylog-plugin-map-widget-1.0.0.jar
> -rw-r--r-- 1 root root 2837117 Apr 28 16:03 graylog-plugin-pipeline-processor-1.0.0-beta.2.jar
> -rw-r--r-- 1 root root  484487 Apr 28 16:03 usage-statistics-2.0.0.jar

note that installation directory is "plugin", not "plugins" as instructed in official documentation.

After restart plugin does not appear:

![image](https://cloud.githubusercontent.com/assets/329079/15024651/ea546624-125f-11e6-9015-0bd7e65f1298.png)

Please help!

**Comment by sivasamyk** [comment]
Can you please attach the graylog-server log files? The plugins loaded will be listed in the log file.

**Comment by sivasamyk** [comment]
@romanr please reopen if it is still reproducible.

**Comment by aramoskeedio** [comment]
Hi

I have the same problem, but the input appear in the log file:

> 2018-03-21T12:47:26.957Z INFO  [CmdLineTool] Loaded plugin: AWS plugins 2.4.3 [org.graylog.aws.plugin.AWSPlugin]
> 2018-03-21T12:47:26.960Z INFO  [CmdLineTool] Loaded plugin: Elastic Beats Input 2.4.3 [org.graylog.plugins.beats.BeatsInputPlugin]
> 2018-03-21T12:47:26.963Z INFO  [CmdLineTool] Loaded plugin: CEF Input 2.4.3 [org.graylog.plugins.cef.CEFInputPlugin]
> 2018-03-21T12:47:26.964Z INFO  [CmdLineTool] Loaded plugin: Collector 2.4.3 [org.graylog.plugins.collector.CollectorPlugin]
> 2018-03-21T12:47:26.971Z INFO  [CmdLineTool] Loaded plugin: Enterprise Integration Plugin 2.4.3 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
> 2018-03-21T12:47:26.973Z INFO  [CmdLineTool] Loaded plugin: MapWidgetPlugin 2.4.3 [org.graylog.plugins.map.MapWidgetPlugin]
> 2018-03-21T12:47:26.975Z INFO  [CmdLineTool] Loaded plugin: NetFlow Plugin 2.4.3 [org.graylog.plugins.netflow.NetFlowPlugin]
> 2018-03-21T12:47:26.991Z INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 2.4.3 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
> 2018-03-21T12:47:26.993Z INFO  [CmdLineTool] Loaded plugin: Threat Intelligence Plugin 2.4.3 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
> 2018-03-21T12:47:26.994Z INFO  [CmdLineTool] Loaded plugin: Anonymous Usage Statistics 2.3.0 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
> **2018-03-21T12:47:26.994Z INFO  [CmdLineTool] Loaded plugin: HttpMonitorInput 1.0.5 [org.graylog2.plugin.httpmonitor.HttpMonitorInputPlugin]**
> 2018-03-21T12:47:27.715Z INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=rpm
> 2018-03-21T12:47:28.135Z INFO  [Version] HV000001: Hibernate Validator 5.1.3.Final
