### ISSUE TITLE
HTTPS doesn't work

### ISSUE THREAD

**Issue by ludekvodicka** [sivasamyk/graylog2-plugin-input-httpmonitor#8]
I'm getting following error when trying https web (for example https://www.skipper18.com)

Request failed :java.net.ConnectException: Received fatal alert: internal_error

**Comment by sivasamyk** [comment]
@ludekvodicka I tried monitoring  https://www.skipper18.com from my local graylog installation and it works fine. I am able to get the HTML response. Do you have any proxy server in between graylog & the web server? Can you let me know any other https endpoints where you are able to reproduce this issue?

**Comment by ludekvodicka** [comment]
There is no proxy between Graylog and web. Graylog is running inside the docker based on recommended image (graylog2/server:2.1.0-3).

It seems that any of our websites which using https:// through Cloudflare doesn't work (next example https://pulpo18.com). But other https sites work ok. Is there any detailed log to see better error message?

This is my complete testing configuration together with elastic and mongo, graylog login admin:admin

version: '2'
services:

  dum-graylog-mongo:
    container_name: dum-graylog-mongo 
    image: "mongo:3"
    volumes:
    - /data/db
    
  dum-graylog-elasticsearch:
    container_name: dum-graylog-elasticsearch
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /usr/share/elasticsearch/data
      
  dum-graylog:
    container_name: dum-graylog
    image: graylog2/server:2.1.0-3
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    depends_on:
      - dum-graylog-mongo
      - dum-graylog-elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
    volumes:      
      - ./graylog/data/graylog/data/config:/usr/share/graylog/data/config
      - /usr/share/graylog/data/journal
      - ./graylog/data/graylog/log:/usr/share/graylog/log 
      - ./graylog/data/graylog/plugin:/usr/share/graylog/plugin

**Comment by sivasamyk** [comment]
looks like this issue has something to with SNI ( Server Name Indication). Can  you let me know the java version used to run graylog ( Java 7 or 8)? Meanwhile I will check if there is any fix possible.

**Comment by ludekvodicka** [comment]
I'm using prepared graylog docker image (graylog2/server:2.1.0-3) and this is java version:

```
root@e551f2a673f6:/usr/share/graylog# java -showversion
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by sivasamyk** [comment]
@ludekvodicka Can you please test with attached plugin and let me know if it works. (make sure you restart graylog server after replace the plugin jar). Please unzip the attachment.

[graylog2-plugin-input-httpmonitor-1.0.3.jar.zip](https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/files/697001/graylog2-plugin-input-httpmonitor-1.0.3.jar.zip)

**Comment by ludekvodicka** [comment]
Perfect, it works!  - https://dl.dropboxusercontent.com/u/11355235/ShareX/2017/01/2017-01-10_19-46-07.png

Thank you

**Comment by sivasamyk** [comment]
👍 . I have upgraded async http client lib to latest version. will push the changes.
