### ISSUE TITLE
HttpMonitor fixed message lenght

### ISSUE THREAD

**Issue by ludekvodicka** [sivasamyk/graylog2-plugin-input-httpmonitor#9]
Hi,
maybe I overlooked something but I can't find any way how to access more than 50 characters from event message. Is this some hard-coded limitation?

**Comment by sivasamyk** [comment]
Yes. 50 chars is hard coded limit for short_message. You can enable `Log full response body` in the input configuration. This will log the complete response in full_message field.

**Comment by ludekvodicka** [comment]
Perfect. Thanks for reply. I overlooked this checkbox.
